### ISSUE TITLE
项目启动失败！

### ISSUE THREAD

**Issue by konzilmxp** [MQPearth/Blog#1]
Failed to auto-configure a DataSource: 'spring.datasource.url' is not specified and no embedded datasource could be auto-configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**Comment by MQPearth** [comment]
猜测：可能是配置文件的问题，我这边本地是没有问题的，毕竟就一个报错我也看不出什么
