### ISSUE TITLE
关于 本地部署启动后，后端显示sql报错 的问题

### ISSUE THREAD

**Issue by ZigHuang** [MQPearth/Blog#14]
我在docker配置好其他服务后，在本地启动前、后端项目后，前端页面如图

<img width="1530" alt="截屏2021-12-08 下午11 12 31" src="https://user-images.githubusercontent.com/75672325/145232749-2757ddaf-0619-46c9-9ecf-536070fd8a66.png">

查看后端log日志，发现如下
<img width="1665" alt="截屏2021-12-08 下午11 13 47" src="https://user-images.githubusercontent.com/75672325/145232949-ab0e19ba-be4e-40eb-9c57-2a262508f769.png">

我想询问一下这个问题该怎么解决呢？

**Comment by Super-ZZGuo** [comment]
相比于在docker部署，在本地部署的差别 是我**本地没有配置nginx**，这是否会导致这个问题的原因呢？

**Comment by Super-ZZGuo** [comment]
> 相比于在docker部署，在本地部署的差别 是我**本地没有配置nginx**，这是否会导致这个问题的原因呢？

刚刚我打包到docker部署，前端也同样显示上面的“服务异常，请联系管理员”，其中我尝试访问8001端口(此时已经配置好nginx)，如图
![image](https://user-images.githubusercontent.com/75672325/145236351-91e1c3ed-9bb8-42ab-9e5a-aaa8ed7f90e3.png)
不知道我这样是哪里出了问题

**Comment by ZigHuang** [comment]
问题已经解决，主要是mysql版本的问题，5.7版本以上默认开启only_full_group_by
我关闭了5.7版本的 sql_mode="ONLY_FULL_GROUP_BY" 就没有报错了

**Comment by Super-ZZGuo** [comment]
> 问题已经解决，主要是mysql版本的问题，5.7版本以上默认开启only_full_group_by
> 我关闭了5.7版本的 sql_mode="ONLY_FULL_GROUP_BY" 就没有报错了

这个问题无法复现，我开启后 sql_mode="ONLY_FULL_GROUP_BY"  🤣依然没有报错了。。。
