### ISSUE TITLE
用户注册验证码不正确的问题

### ISSUE THREAD

**Issue by ZigHuang** [MQPearth/Blog#15]
我在进行用户注册时报 **邮箱验证码不正确** 的错误
> 发现是 redis存储key value的问题

redis存储的code值(验证码) 相比 邮箱发送 的多了一个**邮箱发送状态**
例如邮箱发送code值(验证码)为`854570`
而此时Redis存入的值为`854570_1`(1表示邮箱发送成功)
当用户注册的时候，后台通过Redis查出的Key值进行**对比**会返回错误

**Comment by MQPearth** [comment]
不想维护了, 大佬来个pull request吧

**Comment by ZigHuang** [comment]
已提Pr🤣

**Comment by MQPearth** [comment]
https://github.com/MQPearth/Blog/pull/17
