### ISSUE TITLE
考虑为每个功能模块写一份说明文档

### ISSUE THREAD

**Issue by ZigHuang** [MQPearth/Blog#18]
我认为这个项目对于Java入门者来说依然是个很好的项目：
- 使用了Spring的AOP进行日志的拦截
- 使用了MVC映射本地静态资源实现图片访问
- 对于Redis和数据库的数据一致性和消息队列的使用也很值得深究
- Security+JWT+Redis的认证方式学习到很多东西
- 前端的使用也并不繁杂，对于有前端基础的Java入门者来说依然能做一些自定义样式修改
- 深入考虑也能思考单机下的并发控制（使用JUC或synchronized

我能否为该项目写一份简单的功能模块说明文档呢🤣

**Comment by MQPearth** [comment]
你写吧
