### ISSUE TITLE
删除博客对归档统计的影响

### ISSUE THREAD

**Issue by ZigHuang** [MQPearth/Blog#20]
**归档统计**时并没有对**已删除博客做一个筛选**(已提PR)
- 状态为0的博客依然会被统计进去

亦或是说**归档统计**本就是统计包括已删除的所有博客？(如果是这样，请无视🤣，然而，删除博客后依然会对Redis的归档信息做一个删除，显得有些多余了)

**Comment by MQPearth** [comment]
https://github.com/MQPearth/Blog/pull/19

**Comment by MQPearth** [comment]
方便给个联系方式吗, 方便的话请通过邮箱私发给我 1970432392@qq.com
