### ISSUE TITLE
博客首页查看时，当部分博客存在于缓存中，其余需要查询MySQL时，是否忘记使用tagDao进行博文的标签设置？

### ISSUE THREAD

**Issue by LTH-S** [MQPearth/Blog#21]
请问在com.zzx.service.BlogService的
```java
public List<Blog> findHomeBlog(Integer page, Integer showCount)
```
方法里，设置缓存的部分，有三个分支，也就是①不在缓存，②部分在缓存，③全部在缓存。
通过读您的代码可以了解到，tag标签是通过tagDao来根据博客id来获取到并设置到blog对象的。
在第①个情况，不在缓存时，是通过blogDao获取到博文数据后再通过tagDao来设置博文标签的。
但是在第②个情况里，也就是部分在缓存的情况中，在查询MySQL后的结果中是没有看见有使用到tagDao来设置博文标签的，请问这个是否是一个bug，或是别的地方有所设置。

**Comment by ZigHuang** [comment]
同意你说的情况，
- 然而，在主页上似乎没有发现因此而造成的bug？
- 实际上redis会一直缓存所有的博客，我认为通过NEWBLOG来判断，是否要再次从mysql中获取博客数据，这个步骤有点多余？

**Comment by LTH-S** [comment]
1. 是的，通过debug，我发现不会造成bug的原因是该程序实际上并不会执行第二种情况
也就是部分在缓存的情况，因为每次的start都是5的整数倍，showCount也始终是5（在前端定死了）
所以根本不会有
`start + showCount > RedisConfig.REDIS_NEW_BLOG_COUNT`
也就是 5\*n + 5 > 10的情况出现，所以该分支不会执行。
只会有 5\*n + 5 = 10 和 5\*n + 5 < 10的情况发生，也就是①③情况
但是如果前端的start和showCount发生了更改，可能会造成意想不到的错误。

2. 由于所有的博客都会缓存到Redis中，而NEWBLOG值始终是10，通过NEWBLOG来判断确实是多余了，其实我认为作者设计的时候应该想表达的意思是只在Redis中缓存NEWBLOG数量值的博客，也就是最新创建的10篇博客，使用Redis的目的也在于此，毕竟只有首页博客被浏览的次数较多，才有必要使用缓存。
如果将全部博客进行缓存，当博客数量较大时这么做是不合理的。而作者在实际中并没有这么做，导致该部分代码写的并不是很好。不过总体设计思路还是很不错的，值得学习。

**Comment by ZigHuang** [comment]
you are right. 针对这两点,欢迎发起PR👍

**Comment by ZigHuang** [comment]
> * 是的，通过debug，我发现不会造成bug的原因是该程序实际上并不会执行第二种情况
>   也就是部分在缓存的情况，因为每次的start都是5的整数倍，showCount也始终是5（在前端定死了）
>   所以根本不会有
>   `start + showCount > RedisConfig.REDIS_NEW_BLOG_COUNT`
>   也就是 5*n + 5 > 10的情况出现，所以该分支不会执行。
>   只会有 5*n + 5 = 10 和 5*n + 5 < 10的情况发生，也就是①③情况
>   但是如果前端的start和showCount发生了更改，可能会造成意想不到的错误。

当page - 1 发生变化时，不会出现②的问题嘛(出现 5 * 2 + 5 > 10的情况)，还是说前端也是把传入的 page 写死了？
PS：我环境有点问题，暂时测试不了。。。

**Comment by LTH-S** [comment]
仔细阅读该段代码可以发现，第①个情况中
`if (start >= RedisConfig.REDIS_NEW_BLOG_COUNT)`
你列举的5 * 2 + 5 > 10的情况会走第一个分支，不再走第二个分支

**Comment by LTH-S** [comment]
刚刚没有解释清楚，抱歉

**Comment by ZigHuang** [comment]
😂忘了第一个分支了

**Comment by MQPearth** [comment]
原来还有这么个issue, 这么久过去了, 我都感觉这不是我写的代码了.
