### ISSUE TITLE
There is a SQL injection vulnerability in Blog/blog-springboot/src/main/java/com/zzx/controller /BlogController.java

### ISSUE THREAD

**Issue by N0boy-0** [MQPearth/Blog#45]
![sql1](https://github.com/MQPearth/Blog/assets/63273184/008c2839-03a4-4113-b4f5-3429d850a426)
![sql2](https://github.com/MQPearth/Blog/assets/63273184/46f31d42-d7b1-4eb2-bda8-e1ae96e4ca39)

Direct use of "${}" in Mapper files will bring the risk of SQL injection.
We can use boolean blind injection to attack the database.
![sql3](https://github.com/MQPearth/Blog/assets/63273184/9f149243-fba6-45cb-ae5e-76c8cf778e79)
![sql4](https://github.com/MQPearth/Blog/assets/63273184/b22cb6fb-ab61-4b57-b8a7-d6fdc0d4e9cf)

![sql5](https://github.com/MQPearth/Blog/assets/63273184/1d795e7b-4ebe-4d83-a68d-072e361461ab)

**Comment by MQPearth** [comment]
https://github.com/MQPearth/Blog/issues/46#issuecomment-1851839982

**Comment by MQPearth** [comment]
https://github.com/MQPearth/Blog/commit/678664971e4451595732f362fd9b71c22dc0e4b7
