### ISSUE TITLE
There is a SQL injection vulnerability in blog-springboot/src/main/java/com/zzx/controller/UserController.java

### ISSUE THREAD

**Issue by N0boy-0** [MQPearth/Blog#46]
![sql1](https://github.com/MQPearth/Blog/assets/63273184/a06593a6-d555-4fa5-9507-9d843894781b)
![sql2](https://github.com/MQPearth/Blog/assets/63273184/5c0af243-16de-4ba9-8955-51ad3b83c01a)
Direct use of "${}" in Mapper files will bring the risk of SQL injection.

Databases are vulnerable to SQL injection attacks.
![sql3](https://github.com/MQPearth/Blog/assets/63273184/9c3c4750-7d03-4d07-ba0d-5e0f06bbbe0b)
![sql4](https://github.com/MQPearth/Blog/assets/63273184/f000783b-b3c0-4c10-9cc8-0144268ea052)

**Comment by MQPearth** [comment]
You are correct; it will be fixed shortly.

**Comment by MQPearth** [comment]
https://github.com/MQPearth/Blog/commit/678664971e4451595732f362fd9b71c22dc0e4b7
